import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

export default function Layaout ({children}){

    return (
        <>
            <Head>
                <title>hexalud</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.webp" />
            </Head>
            <header>
                <div className='logo'>
                    <Image src="/logo.webp" alt="hexalud" width={50} height={50}/>
                </div>
                <nav>
                    <p className='nav-link'>Blog</p>
                </nav>
            </header>
            {children}
        </>
    )
}